### ISSUE TITLE
[Bug]: Wire Spaghetti unable to progress past "Watched state 0 should point to a register [...]"

### ISSUE THREAD

**Issue by IcedHybrid** [Turing-Complete-Game/Suggestions-and-Issues#280]
While constructing the new Leg architecture in the level "Wire Spaghetti", I am unable to satisfy the game requirements (both guidance and actual run-time requirement) of "Watched state 0 should point to a register or custom component with a register inside". 
Reproduction case: I created a new schematic, placed the bare minimum 4 byte program + counter + 6 1 byte memory registers. This satisfies all guidance requirements up until that point. Then toggling the Edit Watched State and connecting the program watch pins to each register does not progress the guidance. It also re-asserts this requirement at attempted run.
I hope this isn't something I'm overlooking, but this bare-minimum repro seems broken as well as my actual attempt at the Leg architecture.
![GuidanceBroken](https://user-images.githubusercontent.com/36185662/151691248-1185e1e6-67f2-423a-b93c-e4286520293d.PNG)
![ExecutionBroken](https://user-images.githubusercontent.com/36185662/151691249-67e44aa1-f1cb-4e6a-8a0f-fe79fc1549db.PNG)

This occurs for me on both Latest and Development

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Quashqwart** [comment]
Watch states seem to work with 1-byte memory, but not with 4-byte on level Wire Spaghetti

**Comment by kevin-frugier** [comment]
Same here on 0.487 Beta
since the latest patch 
![image](https://user-images.githubusercontent.com/9249864/151705180-3fe1c29a-72cd-44af-a189-90f7b52a398d.png)

Despite having properly added a watched state to the existing "Register Plus" (as required by the update), the wire spaghetti level no longer works and all levels above are broken (even though they previously worked and I had only 2 levels remaining to beat the game :( )

**Comment by Windows95Experience** [comment]
This issue really needs fixed, as I'm stuck with the same problem

**Comment by hogiyogi597** [comment]
I think this is the same issue, if I am understanding correctly. But I can't attach watched state to the `Register Plus` custom component... I can't progress in the game because of it 😞 Was looking forward to pushing further today.

![image](https://user-images.githubusercontent.com/25204032/151721062-8443e8eb-69cc-4145-a8b2-dd9ab95e3703.png)

**Comment by Windows95Experience** [comment]
@hogiyogi597 You need to add the new "Byte Watch" component to the RegisterPlus component, and then connect the watched state on the register to that new byte watch component, so no, your issue is not the same, nor is it a bug. But once you do what I said to do, you will run into the same issue that me and other people are experiencing, where the game doesn't recognize that the watched state on the RegisterPlus is connected to the Program component, and thus makes progression impossible.

**Comment by Stuffe** [comment]
This should have been fixed now in the latest patch.

**Comment by kevin-frugier** [comment]
This is indeed fixed for registers but not for watch state 7 linked to output : 
https://youtu.be/6X5S3HvIGTA

**Comment by Stuffe** [comment]
> This is indeed fixed for registers but not for watch state 7 linked to output : https://youtu.be/6X5S3HvIGTA

Create a new schematic and start over there, that should make it work.

**Comment by kevin-frugier** [comment]
In 0.491 it works fine (had to reconnect the registers once again but now everything is properly validated by the game)

**Comment by Quashqwart** [comment]
v 0.495
i'm still having problems on wire spaghetti

I can watch state of vanilla register, but i can't watch state of RegisterPlus (even after adding "watch byte" to RegisterPlus schematic and connecting it to the register state)

Moreover, value written on the RegisterPlus does not reflect it's state - it says 0 all the time

**Comment by Stuffe** [comment]
> v 0.495 i'm still having problems on wire spaghetti
> 
> I can watch state of vanilla register, but i can't watch state of RegisterPlus (even after adding "watch byte" to RegisterPlus schematic and connecting it to the register state)
> 
> Moreover, value written on the RegisterPlus does not reflect it's state - it says 0 all the time

The new version 0.496 works, right?

**Comment by tbe** [comment]
I have the same issue in 0.561 with custom components.

**Comment by tbe** [comment]
> I have the same issue in 0.561 with custom components.

Works again in 0.563 beta
